import Head from 'next/head';
import Link from 'next/link';
import { isEmpty } from 'lodash';
import { useContext, useState } from 'react';

import { TailwindIcon, User, Bag, Wishlist, BurgerIcon } from '../../icons';
import { AppContext } from '../../context';

const Header = ({ header }) => {
  const [cart, setCart] = useContext(AppContext);

  const { headerMenuItems, siteDescription, siteLogoUrl, siteTitle, favicon } = header || {};

  const [isMenuVisible, setMenuVisibility] = useState(false);

  return (
    <>
      <Head>
        <title>{siteTitle || 'Nextjs Woocommerce Website'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={favicon || '/favicon.ico'} />
      </Head>
      <div className="header">
        <nav className="bg-white p-4">
          <div className="flex items-center justify-between flex-wrap container mx-auto">
            <div className="flex items-center flex-shrink-0 text-black mr-20">
              <Link href="/">
                {siteLogoUrl ? (
                  <a>
                    <img className="mr-3" src={siteLogoUrl} alt={`${siteTitle} Logo`} width="100" />
                  </a>
                ) : (
                  <a className="font-thin">
                    {siteTitle || 'WooNext'}
                    {siteDescription ? <span className="text-sm"> - {siteDescription}</span> : null}
                  </a>
                )}
              </Link>
            </div>
            <div className="block lg:hidden">
              <button
                onClick={() => setMenuVisibility(!isMenuVisible)}
                className="flex items-center px-3 py-2 border rounded text-black border-black hover:text-black hover:border-black">
                <BurgerIcon className="fill-current h-3 w-3" />
              </button>
            </div>
            <div className={`${isMenuVisible ? 'max-h-full' : 'h-0'} overflow-hidden w-full lg:h-full block flex-grow lg:flex lg:items-center lg:w-auto`}>
              <div className="text-sm font-medium uppercase lg:flex-grow">
                {!isEmpty(headerMenuItems) && headerMenuItems.length
                  ? headerMenuItems.map(menuItem => (
                      <Link key={menuItem?.ID} href={menuItem?.url || '/'}>
                        <a
                          className="block mt-4 lg:inline-block lg:mt-0 text-black hover:text-black mr-10"
                          dangerouslySetInnerHTML={{ __html: menuItem.title }}
                        />
                      </Link>
                    ))
                  : null}
              </div>
              <div className="text-sm font-medium">
                <a href="#responsive-header" className="flex mt-4 lg:inline-block lg:mt-0 text-black hover:text-black mr-10">
                  <span className="flex flex-row items-center lg:flex-col">
                    <User className="mr-1 lg:mr-0" />
                    Profile
                  </span>
                </a>
                <a href="#responsive-header" className="flex mt-4 lg:inline-block lg:mt-0 text-black hover:text-black mr-10">
                  <span className="flex flex-row items-center lg:flex-col">
                    <Wishlist className="mr-1 lg:mr-0" />
                    Wishlist
                  </span>
                </a>
                <Link href="/cart">
                  <a className="flex mt-4 lg:inline-block lg:mt-0 text-black hover:text-black mr-10">
                    <span className="flex flex-row items-center lg:flex-col">
                      <Bag className="mr-1 lg:mr-0" />
                      <span className="ml-1">Bag{cart?.totalQty ? `(${cart?.totalQty})` : null}</span>
                    </span>
                  </a>
                </Link>
              </div>
            </div>
          </div>
        </nav>
      </div>
    </>
  );
};

export default Header;
